language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r dev-requirements.txt --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py develop
# command to run tests, e.g. python setup.py test
script: nosetests