sudo: false
cache: pip
language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # Setup of Git environment
  - git config --global user.email user@example.com
  - git config --global user.name "Travis CI"

  # Setup of Python environment
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: nosetests -v --with-coverage --cover-package=PyGitUp

after_success:
  - coveralls
